name: clearvote
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2023.7.22
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=1.1.1v
  - pip=23.2.1
  - python=3.9.6
  - readline=8.2
  - setuptools=68.1.2
  - sqlite=3.42.0
  - tk=8.6.12
  - wheel=0.41.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - anyio==3.7.1
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astroid==2.15.6
      - asttokens==2.2.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - black==23.7.0
      - bleach==6.0.0
      - blinker==1.6.2
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - comm==0.1.4
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fiona==1.9.4.post1
      - flask==2.3.3
      - flask-wtf==1.1.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - geopandas==0.13.2
      - google-api-core==2.11.1
      - google-auth==2.22.0
      - google-cloud-secret-manager==2.10.0
      - googleapis-common-protos==1.60.0
      - grpc-google-iam-v1==0.12.6
      - grpcio==1.57.0
      - grpcio-status==1.57.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - isort==5.12.0
      - itsdangerous==2.1.2
      - jedi==0.19.0
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - lazy-object-proxy==1.9.0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mistune==3.0.1
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.7.4
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - notebook==7.0.2
      - notebook-shim==0.2.3
      - numpy==1.25.2
      - openai==0.28.0
      - overrides==7.4.0
      - packaging==23.1
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathlib==1.0.1
      - pathspec==0.11.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - proto-plus==1.22.3
      - protobuf==4.24.2
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.16.1
      - pylint==2.17.5
      - pyproj==3.6.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.9.2
      - rsa==4.9
      - send2trash==1.8.2
      - shapely==2.0.1
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.12.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3 # TODO: add a version. The most recent version was preventing google cloud secret storage from working 
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.3.7
      - widgetsnbextension==4.0.8
      - wrapt==1.15.0
      - wtforms==3.0.1
      - yarl==1.9.2
      - zipp==3.16.2
prefix: /Users/anayap/anaconda3/envs/clearvote